/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData favoritos = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menos = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mas = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usuario = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basura = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alerta = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendario = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flecha1 = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flecha = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
